# frozen_string_literal: true

source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '3.0.0'

# Rails
gem 'rails', '~> 7.0.0'

# API-specific gems
gem 'bootsnap', '>= 1.4.4', require: false
gem 'rack-cors'
gem 'shopify_app', '~> 21.2'

# For JSON handling
gem 'oj'

group :development, :test do
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
end

group :development do
  gem 'listen', '~> 3.3'
  gem 'spring'
end